name: tic_tac_toe
description: "Flutter Technical Test"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  shared_preferences: ^2.5.4
  json_annotation: ^4.10.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.5
  freezed: ^3.2.4
  json_serializable: ^6.12.0

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
