name: tic_tac_toe
description: "BetClic Technical Test Project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- STATE MANAGEMENT  ---
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # --- DATA & MODELS ---
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2

  # --- UI & ROUTING ---
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # --- CODE GENERATION ---
  build_runner: ^2.4.11
  riverpod_generator: ^2.6.1
  freezed: ^2.5.7
  json_serializable: ^6.8.0

  # --- LINTER ---
  flutter_lints: ^4.0.0

  # --- TESTS ---
  mockito: ^5.4.4

  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21